"""is_admin column

Revision ID: 44129a6f3f87
Revises: 
Create Date: 2019-06-15 22:15:33.635647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44129a6f3f87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'is_admin')
    # ### end Alembic commands ###
